### ISSUE TITLE
Code Update

### ISSUE THREAD

**Issue by mash2612** [srihari-humbarwadi/cityscapes-segmentation-with-Unet#1]
Hi,
Thanks for your amazing code. I have a question in the code of batch_training.py
In the class Visualize() we have in lines 146- 148 for three classes. However, if we have to do it for 8 classes this code has to be updated in the same way as it is done for "inference.ipynb". Is my understanding correct?
Basically this piece of code:(From "batch_training.py")
    def on_epoch_end(self, epoch, logs):
        print(f'\nGenerating output at epoch : {epoch}')
        i = 567
        img = image.img_to_array(image.load_img(f'{image_dir}/{image_list[i]}'))/255.    
        dims = img.shape
        x = cv2.resize(img, (256, 256))
        x = np.float32(x)/255.
        z = unet.predict(np.expand_dims(x, axis=0))
        z = np.squeeze(z)
        z = z.reshape(256, 256, 8)
        z = cv2.resize(z, (dims[1], dims[0]))
        y = np.argmax(z, axis=2)
        
        construction = np.zeros_like(y)
        human = np.zeros_like(y)
        vehicle = np.zeros_like(y)
        construction[y==2] = 255.
        human[y==6] = 255.
        vehicle[y==7] = 255.
        
        result = img.copy()
        alpha = 0.4
        img[:,:,1] = construction
        img[:,:,2] = vehicle 
        img[:,:,0] = human

should be replaced by(I edited based on my understanding from inference.ipynb):

def on_epoch_end(self, epoch, logs):
        print(f'\nGenerating output at epoch : {epoch}')
        alpha = 0.6
        i = 567
        img = image.img_to_array(image.load_img(f'{image_dir}/{image_list[i]}'))/255.
        dims = img.shape
        x = cv2.resize(img, (256, 256))
        x = np.float32(x)/255.
        z = unet.predict(np.expand_dims(x, axis=0))
        z = np.squeeze(z)
        z = z.reshape(256, 256, 8)
        z = cv2.resize(z, (dims[1], dims[0]))
        y = np.argmax(z, axis=2)

        color_map = {
        '0': [0, 0, 0],
        '1': [153, 153, 0],
        '2': [255, 204, 204],
        '3': [255, 0, 127],
        '4': [0, 255, 0],
        '5': [0, 204, 204],
        '6': [255, 0, 0],
        '7': [0, 0, 255]
        }
       img_color = img.copy()
        for i in range(dims[0]):
            for j in range(dims[1]):
                img_color[i,j] = color_map[str(y[i, j])]
        cv2.addWeighted(img, alpha, result, 1-alpha, 0, result)

is this correct?

**Comment by srihari-humbarwadi** [comment]
Here is a better way to do it, please check the inference.py in [https://github.com/srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0](https://github.com/srihari-humbarwadi/DeepLabV3_Plus-Tensorflow2.0)
